{
  parserClass="com.github.suzumaze.intellijqiqplugin.parser.QiqParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Qiq"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.suzumaze.intellijqiqplugin.psi"
  psiImplPackage="com.github.suzumaze.intellijqiqplugin.psi.impl"

  elementTypeHolderClass="com.github.suzumaze.intellijqiqplugin.psi.QiqTypes"
  elementTypeClass="com.github.suzumaze.intellijqiqplugin.psi.QiqElementType"
  tokenTypeClass="com.github.suzumaze.intellijqiqplugin.psi.QiqTokenType"
}

qiqFile ::= item_*

private item_ ::= (property|CRLF|PHP_BLOCK)

property ::= (KEY? SEPARATOR VALUE?) | KEY

PHP_BLOCK ::= QIQ_OPENING_TAG PHP_CONTENT QIQ_CLOSING_TAG
             | QIQ_ECHO_OPENING_TAG PHP_CONTENT QIQ_CLOSING_TAG